### ISSUE TITLE
[Question] Parameters + Empty Responses

### ISSUE THREAD

**Issue by Owen-Oertell** [kvablack/LLaVA-server#4]
Hello, I was trying to recreate the figures in the DDPO paper, and I wanted to seek some clarification as to how many parameters were used of LLaVA for the DDPO paper? I also got this server to work with 7B llava, but the issue that I was running into was that sometimes the model would output nothing and resulted in a bertscore of 0. Was this the case in the figures used for the DDPO paper? Also, at about how many iterations were the figures in the paper taken? Thanks.

**Comment by kvablack** [comment]
I used the 13B version of LLaVA. As far as I know, I never had a problem with the model outputting nothing.

Not sure what you mean by the number of iterations -- the paper reports # of reward queries, which you can map back to epochs by dividing by the total batch size (which is 256).

**Comment by bhattg** [comment]
I've also observed this issue w/ LLaVA-7B. But the same gives response string w/ LLaVA-13B. I don't have a solution for this, but happy to see I'm not the only one facing this issue.

**Comment by Owen-Oertell** [comment]
If you replace in the prompt `answer concisely` with `answer concisely, but not empty`, I was able to prevent the model from outputting nothing. I only tested this on the LLaVA-7B though.
