### ISSUE TITLE
cannot import name 'simple_conv_multimodal' from 'llava.conversation'

### ISSUE THREAD

**Issue by rkuo2000** [kvablack/LLaVA-server#8]
gunicorn "app:create_app()"

  File "/home/rkuo/GenAI/Image-to-Text/LLaVA-server/llava_server/llava.py", line 9, in <module>
    from llava.conversation import simple_conv_multimodal
ImportError: cannot import name 'simple_conv_multimodal' from 'llava.conversation' (/home/rkuo/LLaVA/llava/conversation.py)

**Comment by rumi-ali** [comment]
That is my issue as well. found any solution?

**Comment by rkuo2000** [comment]
Just use conda to create venv, then go along with the installation instructions

**Comment by kubs0ne** [comment]
Hey, I still have this error, tried creating conda env and it still persists
